name: Run Unit Tests

on:
  push:
    branches:
      - new_features_414014

jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python (if needed)
        if: runner.os == 'Linux' || runner.os == 'Windows'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Unit Tests
        run: python -m unittest test_geometric.py
        shell: bash
